<?xml version="1.0" encoding="UTF-8"?><testrun name="JUnitRechner" project="Praktikum pmp2 WS15" tests="10" started="10" failures="0" errors="1" ignored="0">
  <testsuite name="aufgabenblatt2.JUnitRechner" time="0.063">
    <testcase name="testNix" classname="aufgabenblatt2.JUnitRechner" time="0.052">
      <error>java.lang.NullPointerException&#13;
	at aufgabenblatt2.Rechner.berechne(Rechner.java:47)&#13;
	at aufgabenblatt2.JUnitRechner.testNix(JUnitRechner.java:106)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</error>
    </testcase>
    <testcase name="test1" classname="aufgabenblatt2.JUnitRechner" time="0.009"/>
    <testcase name="test2" classname="aufgabenblatt2.JUnitRechner" time="0.0"/>
    <testcase name="test3" classname="aufgabenblatt2.JUnitRechner" time="0.0"/>
    <testcase name="test4" classname="aufgabenblatt2.JUnitRechner" time="0.0"/>
    <testcase name="test5" classname="aufgabenblatt2.JUnitRechner" time="0.0"/>
    <testcase name="test6" classname="aufgabenblatt2.JUnitRechner" time="0.0"/>
    <testcase name="test7" classname="aufgabenblatt2.JUnitRechner" time="0.0"/>
    <testcase name="test8" classname="aufgabenblatt2.JUnitRechner" time="0.0"/>
    <testcase name="test9" classname="aufgabenblatt2.JUnitRechner" time="0.001"/>
  </testsuite>
</testrun>
